Feature/1 move license checker to repo
cloudogu/confluence-license-checker pull request #2
Opened 2020-07-17 11:23 UTC by ppxl

This PR moves the license-checker code from the confuence repo to this repo and makes some necessary adjustments

resolves #1

2020-07-17 11:24 UTC, cesmarvin commented on license/watcher/watcher.go
> +	for range time.Tick(duration) {
**[checkstyle]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
SA1015: using time.Tick leaks the underlying ticker, consider using it only in endless functions, tests and the main package, and use time.NewTicker here

2020-07-17 14:16 UTC, ppxl commented on license/watcher/watcher.go
> +	for range time.Tick(duration) {
resolved by ignoring. Given its purposes (trivial) and its runtime (short) using `time.Ticker` is okay compared to its more complex alternative:

```
time.Tick(duration)
...
vs
...
ticker := time.NewTicker(time.Second)
defer ticker.Stop() 
done := make(chan bool) 
go func() {
    time.Sleep(10 * time.Second)
    done <- true 
}() 
for {
    select {
    case <-done:
        fmt.Println("Done!")
        return
    case t := <-ticker.C:
        fmt.Println("Current time: ", t)
    }
}
```

2020-07-22 05:25 UTC, sklein94 requested changes

2020-07-22 05:25 UTC, sklein94 commented on Jenkinsfile
> +}
Github complaints about a missing newline at the end of the file

2020-07-22 05:25 UTC, sklein94 commented on Jenkinsfile
> +        }
I think we should use the sonar branch plugin here. You can almost copy it from the jenkinsfile in cesapp or doguctl.

2020-07-22 05:25 UTC, sklein94 commented on Jenkinsfile
> +                sh "${scannerHome}/bin/sonar-scanner -Dsonar.projectName=${repositoryName}:${env.BRANCH_NAME} -Dsonar.projectKey=$repositoryName -Dsonar.sources=. -Dsonar.junit.reportsPath=target/uni
To make this very long line shorter you can use a `sonar-project.properties`-file for `sonar.exclusions`, `sonar.test.exclusions`, `sonar.test.inclusions`, `junit.reportPaths`, `go.coverage.reportPaths`

2020-07-22 09:32 UTC, merged